Models/ApiResponseModel.cs
using Newtonsoft.Json.Linq;


namespace AAGL_2023.Models
{
    public class ApiResponseModel
    {
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? Credentials { get; set; }
        public string? Email { get; set; }
        public string? Company { get; set; }
        public string? Address1 { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? Zip { get; set; }
        public string? MemberID { get; set; }


        public ApiResponseModel(string allData)
        {
            
            JObject objData = JObject.Parse(allData);
            bool tryToken = objData.TryGetValue("profiles", StringComparison.OrdinalIgnoreCase, out JToken? myProfileOut);

            if (tryToken)
            {
                JObject _data = JObject.FromObject(myProfileOut.First());

                _data.TryGetValue("[Name | First]", StringComparison.OrdinalIgnoreCase, out JToken? firstName);
                _data.TryGetValue("[Name | Last]", StringComparison.OrdinalIgnoreCase, out JToken? lastName);
                _data.TryGetValue("Credentials", StringComparison.OrdinalIgnoreCase, out JToken? credentials);
                _data.TryGetValue("[Email | Primary]", StringComparison.OrdinalIgnoreCase, out JToken? email);
                _data.TryGetValue("Company/Institution Affiliation", StringComparison.OrdinalIgnoreCase, out JToken? company);
                _data.TryGetValue("[Address | Primary | Line 1]", StringComparison.OrdinalIgnoreCase, out JToken? address1);
                _data.TryGetValue("[Address | Primary | City]", StringComparison.OrdinalIgnoreCase, out JToken? city);
                _data.TryGetValue("[Address | Primary | State]", StringComparison.OrdinalIgnoreCase, out JToken? state);
                _data.TryGetValue("[Address | Primary | Zip]", StringComparison.OrdinalIgnoreCase, out JToken? zip);
                _data.TryGetValue("[Member Number]", StringComparison.OrdinalIgnoreCase, out JToken? memberId);

                FirstName = (firstName != null) ? firstName.ToString() : "";
                LastName = (lastName != null) ? lastName.ToString() : "";
                Credentials = (credentials != null) ? credentials.ToString() : "";
                Email = (email != null) ? email.ToString() : "";
                Company = (company != null) ? company.ToString() : "";
                Address1 = (address1 != null) ? address1.ToString() : "";
                City = (city != null) ? city.ToString() : "";
                State = (state != null) ? state.ToString() : "";
                Zip = (zip != null) ? zip.ToString() : "";
                MemberID = (memberId != null) ? memberId.ToString() : "";



            }

        }

        //  2007701445
        //  36838


    }

}

Models/ErrorViewModel.cs
namespace AAGL_2023.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using AAGL_2023.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AAGL_2023.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ValidateController.cs
using AAGL_2023.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Data.SqlClient;

namespace AAGL_2023.Controllers
{
    public class ValidateController : Controller
    {

        string allData;

        public async Task<string> ValidateCredentials(string userCredentials)
        {

            using (HttpClient client = new())
            {
                client.DefaultRequestHeaders.Add("ATSUN", "AtsWebService");
                client.DefaultRequestHeaders.Add("ATSPW", "@t5@W3853rv1c3");
                client.DefaultRequestHeaders.Add("MEMBERNUMBER", userCredentials);
                client.DefaultRequestHeaders.Add("URLFETCHBYID", "https://aagl.memberclicks.net/api/v1/profile/search");
                client.DefaultRequestHeaders.Add("AUTHGRANTTYPE", "client_credentials");
                client.DefaultRequestHeaders.Add("AUTHUSERNAME", "l84CUyTeSZ118AzJYprY");
                client.DefaultRequestHeaders.Add("AUTHPASSWORD", "ba0eecbf54b2440ea7509e83c325faf0");
                client.DefaultRequestHeaders.Add("Accept", "application/json");

                allData = await client.GetStringAsync("https://localhost:7100/AAGL/fetchbyid");

            }

            ApiResponseModel x = new ApiResponseModel(allData);
            


            return "";
        }












    }
}

Views/Home/Index.cshtml
<div class="body-content home">
    <div class="pic-container">
        @*<img style="width: 100%;" src="~/images/logo.png" alt="Logo">*@
    </div>
    <div class="form" style="text-align: center; margin-top: 20px">
        <p><strong>Sign in with your Member ID for AAGL 2023.</strong></p>
        <div class="input-container">
            <input class="myinput" size="50" id="CredIn" spellcheck="false">
        </div>
        <div id="ERRORLABEL"></div>
        <br />
        <button class="btn btn-warning" id="retry" type="button" onClick="window.location.reload();">Retry</button>
        <button class="btn btn-primary" id="login" text="Enter Email">Sign in with Member ID</button>
    </div>
    <br />
    <p style="margin-bottom: 0; text-align: center;">TEMP TEXT Need Help? Email HERE<a href="mailto:EXAMPLE@EMAIL.org">EXAMPLE@EMAIL.org</a>.</p>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>

<script>
    $(window).on('load', function () {
        //
        // Clear any session variables on page load
        //
        $('#retry').hide();
        ClearSession();
        $("#CredIn").focus();
    });

    $("#login").on('click', function (e) {
        try {
            $('#ERRORLABEL').html("").hide();
            //$('#retry').html("").hide();
            $('#retry').hide();
            $.post(
                //
                // Go into our VAR with $("#CredIn").val() as the parameter for userCredentials
                //
                '@Url.Action("ValidateCredentials", "Validate")',
                { userCredentials: $("#CredIn").val() },
                function (result) {
                    if (result.charAt(0) == '*') {
                        $('#ERRORLABEL').html("No record found for this login.").show();
                        $('#retry').html("Retry").show();
                    }
                    //else {
                    //    //
                    //    // If result does not return an error, go to CertificateIndex
                    //    //
                    //    $('#ERRORLABEL').hide();
                    //    window.location.replace('@Url.Action("CertificateIndex", "Certificate")');
                    //}
                }
            );
        }
        catch (e) {
            $('#ERRORLABEL').html("Unknown Error").hide();
        }
    });

    function ClearSession(result) {
        $.post("@Url.Action("ClearSessionVariables", "Home")");
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AAGL 2023</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.2/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="~/css/site.css">
</head>
<body class="double-border">
    <div class="container">
        <main role="main" id="main">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
</body>
</html>